leaf_devices:
  leaf1:
    system_ip: 10.0.0.1
    router_id: 10.0.0.1
    as_number: 101

    interfaces:
      - name: ethernet-1/49
        subif: 0
        ipv4: 192.168.11.1/30

    bgp:
      peer_group: eBGP-underlay
      neighbors:
        - { address: 192.168.11.2, peer_as: 201 }

  leaf2:
    system_ip: 10.0.0.2
    router_id: 10.0.0.2
    as_number: 102

    interfaces:
      - name: ethernet-1/49
        subif: 0
        ipv4: 192.168.12.1/30

    bgp:
      peer_group: eBGP-underlay
      neighbors:
        - { address: 192.168.12.2, peer_as: 201 }