spine_devices:
  spine1:
    system_ip: 10.0.1.1
    router_id: 10.0.1.1
    as_number: 201
    
    interfaces:
      - name: ethernet-1/1
        subif: 0
        ipv4: 192.168.11.2/30
      - name: ethernet-1/2
        subif: 0
        ipv4: 192.168.12.2/30
    
    bgp:
      peer_group: eBGP-underlay
      neighbors:
        - { address: 192.168.11.1, peer_as: 101 }
        - { address: 192.168.12.1, peer_as: 102 }